language: node_js
node_js:
- 5
branches:
- only:
  - master
env:
  global:
  - secure: r4o0p6h7549bZ3YN3levWLnTgjyOgRMg8gWp5pUNAYewzkbR1iG/SYYvDunNPH4zzhrrIfHv6nHnQ5RbRLI9b1JT5A9tCPFWOdp1y77r/4e+aWVQfC62TY5Bj2APPWXW6d/T5N5v6cZFuGUDq7ps5wNnIFcSXd5Yk0KAn/5fZ21/rVixB71T3O+q9H8ip4w4Enxw86dIdWYjHBsZKA3NbAdOPSiIWkNvUc6rcijG14omdY7/WtEUxrmBSJuCca7ChnNkpNk+BNUvxgeUdOtpZRh5MO1bghy3zloCfcR6dLafEq9joKMtdOedoaoUQrVyIT1B54FWrgRYr/72Z64HruyG6VkNQ06PyApJ3MkKU4XyFZeEC+vkNLnVDV2C5mVCthccsRoFwgnS1B9nLuxoA37PCYGWgnc9wIvST5Q5pQ4KvF7dBPkwDeTytXKYUvSqrhTibu532Bx7/k3In8bU4bFiMMfnIl3oEx15gy5JMvxxjNtfrwsgs4wvVSORrLqgq6DkwhK7CAJ+oKtYv/qPIYeG/Y6sy5sh53tiA6D4R8bt4NbsEiWpBubFEspBtetdHjOrplDFHsygKbZhR54Bz660UVccsRFQydA/F7bAKCCjrJHSF+i9M224i+xCQ06JRI0F0HSasvC49iK46wphAhPt7kOh0qDsTM5jP74jug8=
script:
- npm install -g git-credential-env
- git config credential.helper "env --username=GITHUB_TOKEN"
- git config user.name "Travis CI"
- npm run build
- npm run copy-assets
- npm run deploy
