language: node_js
node_js:
- 5
branches:
- only:
  - master
env:
  global:
    secure: E37H5KtJZIhrjY+BznjDmYxdMACjLuMdwvFRjE6HILgVDtpKUJdpiRzsOSqO1Q99mnbNgRSD0EIeycC2FMwazfNXk3f6b/OpvZ3dK40KEcYYTER6E2aqEymwRqYn6jngwGzegT3yayiRMFboHMJfQMfvLgZpGNcrv6TU783jcE6L99cEzJy32gLEJ4GTeKJiBYJtddGpXpToofCM3t7eHRPjWACRpx77/e6nt0tIbb2/49nGpSHVc7aIzVAy+jY75gZG7z+Fdv1LTIoFWZ1VbtzE2f53Fu89azCXMgOUXR/VQmFykuvKqw0R8mqGo5ZRWn8yXL4P0HQg2uUTR5u9uMxMDbPPevRGlz3wM2jeWNbELd2DgJa2PWY8QbAf6aThL6GUUHcZf9ZYkEuGrivPdPYcnvXHLdIAgzbzH3Pb4kxacWdpcP2/Zdwya/AZ6ovL3efflmXf5hfXRmLz3NTelxU+EYg+Dl60djo9H01ke2riIuSz+PzE5/pL2Rvrsm9mUDz9t/bE7aLPDk1K2gRLuuwbl7XVHQNlAKb5AC7oSYOqF7D96uqPwnZE/kjcR5ztYD8QDRVtR38pGZ89FCHBVO80ZtZRZMTDNVeIpfz860U9ePAEh/aBoeLoXlkgkMsehgyqD/meml1e0S0nZGYuyGrwpeENAH9yuv5eBzLgOvA=
script:
- npm install -g git-credential-env
- git config credential.helper "env --username=GITHUB_TOKEN"
- git config user.name "Travis CI"
- npm run build
- npm run copy-assets
- npm run deploy
